stages:
  - build
  - update_helm_chart
variables:
  APP_NAME: login
  IMAGE_TAG: registry.zzzzzzzzzz.life/root/login/$APP_NAME:$CI_COMMIT_SHORT_SHA
build_image:
  image: docker
  stage: build
  only:
    - dev
  services:
    - docker:dind
  script:
    - docker login -u root -p 123456a@ $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG 

update_helm_chart:
    stage: update_helm_chart
    only:
      - dev
    image: ubuntu:22.04
    before_script:
      - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
      - mkdir -p /home/gitlab-runner/.ssh
      - echo "$SSH_PRIVATE_KEY"
#      - echo "$SSH_PRIVATE_KEY1" > /home/gitlab-runner/.ssh/id_rsa
      - chmod 600 /home/gitlab-runner/.ssh/id_rsa
      - ssh-keyscan gitlab.zzzzzzzzzz.life >> /home/gitlab-runner/.ssh/known-hosts
      - ls -l /home/gitlab-runner/.ssh/known-hosts
      - chmod 644 /home/gitlab-runner/.ssh/known-hosts
        # run ssh-agent
      - eval $(ssh-agent -s)
        # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
#      - echo "$SSH_PRIVATE_KEY1" | tr -d '\r' | ssh-add -
      # Git
      - git config --global user.email "admin@example.com"
      - git config --global user.name "root"
      - git clone git@gitlab.zzzzzzzz.life:root/helm_chart.git
      - cd helm_chart
      - ls -latr
    script:
    # Update Image TAG
#     - sed -i "s/login:.*/$IMAGE_TAG/g" trunglv/login-app/values.yaml
     - sed -i "s/login:.*/login:${CI_COMMIT_SHORT_SHA}/g" trunglv/login-app/values/values_dev.yaml
     - sed -i "s/login:.*/login:${CI_COMMIT_SHORT_SHA}/g" trunglv/login-app/values/values_prod.yaml
     - git add login/test-login-app/values.yaml
     - git commit -am "Update Image"
     - git push
