apiVersion: v1
kind: Secret
metadata:
  name: login
  namespace: default
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5tYmFnZWFzLmxpZmUiOnsidXNlcm5hbWUiOiJsb2dpbiIsInBhc3N3b3JkIjoiZ2xkdC15MzJwb3BETmVmVkcyZlJKN2hRYSIsImF1dGgiOiJiRzluYVc0NloyeGtkQzE1TXpKd2IzQkVUbVZtVmtjeVpsSktOMmhSWVE9PSJ9fX0=
type: kubernetes.io/dockerconfigjson
