apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: deployment-dev.yaml
- path: service-dev.yaml
- path: ingress.yaml

# - target:
#     kind: Ingress
#     name: web-deployment-ing
#   patch: |-
#     - op: replace
#       path: /spec/rules/-host
#       value: dev.trunglv.local
