{{- if .Values.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  labels:
    name: {{ .Release.Name }}-ing
spec:
  ingressClassName: {{.Values.ingress.className}}
  rules:
    - host: {{ toYaml .Values.ingress.hostname | indent 4 }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Release.Name }}-svc
                port:
                  number: {{.Values.ingress.port}}
  {{end}}